### ISSUE TITLE
TypeError: Object(...) is not a function, upgrading from 3.4 to 3.5

### ISSUE THREAD

**Issue by jfanals** [ankane/ahoy.js#53]
I have been successfully using ahoy.js 3.4 inside vuex without any issues. With the following command:

    this._vm.$ahoy.track('start', { id: 'ABC' })

After upgrading to 3.5, when trying to execute the same command I get the following error:

    TypeError: Object(...) is not a function

It gets thrown by this line inside the trackEventNow function

    window.navigator.sendBeacon(eventsUrl(), objectToFormData(data));

I think it might be due to this object-to-formdata upgrade:

   https://github.com/ankane/ahoy.js/commit/cc90625e770901dc8982145d82593b495333781b

What would be the correct way to use the track funcion with the new version of the upgraded object-to-formdata library?

**Comment by ankane** [comment]
Hey @jfanals, which version of `object-to-formdata` do you have installed? It looks like there was a recent breaking change with 4.0.

**Comment by jfanals** [comment]
In the node_modules folder it looks like I am using version `4.0.1`, but I am not specifying it on the `package.json` file, it is the one installed by default by `ahoy.js`.

**Comment by ankane** [comment]
Thanks @jfanals, should be fixed in the commit above.

**Comment by jfanals** [comment]
Thanks for the quick fix!

Could you please bump the version number of `package.json` to `3.7`?

https://github.com/ankane/ahoy.js/blob/master/package.json
